### ISSUE TITLE
AttributeError: module 'config' has no attribute 'local_rank'

### ISSUE THREAD

**Issue by Josoope** [hemingkx/WordSeg#15]
有人用cpu跑吗？总报这个错
Traceback (most recent call last):
  File "D:\pythondata\WordSeg-main\BERT-BiLSTM-CRF\run.py", line 139, in <module>
    if config.local_rank == 0:
AttributeError: module 'config' has no attribute 'local_rank'

**Comment by funworl** [comment]
请问这个问题你解决了吗

**Comment by Josoope** [comment]
> 请问这个问题你解决了吗
没有
